### Assignment- Programming for Data Analysis
***
#### Aaron Donnelly-G00299531
***

#### Investigating the numpy.random package in Numpy

### Section 1- The overall purpose of the numpy.random package


##### NumPy also known as numerical python is a fundamental library for analysing scientifc data using python and is the foundation on which many other python libraries have been built. Numpy was built by an Americandata scientist called Travis Oliphant. NumPy is however open source, with many contributers. The main benefit of NumPy is how it deals with lists. A normal python list is tedious when carrying out calculations across the list. NumPy makes this process much more efficient by its ablility to carry out the calculation across entire lists known as numpy arrays(nparray). Numpy is a very important python library in the ever growing areas of neural networks and artificial intelligence. Numpy.random is a sub package of the Numpy library. This package is primarly used to generate random numbers for a user i.e. numbers that cannot be predicted logically [2]. The ability to generate random numbers is a big business in this day and age. The area of cryptography is  heavily reliant on the ability to use random numbers along with much of the current popular game shows. Random numbers are also used in areas such as gambling and can be used to simulate many of these games from ones computer. In the science field random numbers can be used to simulate potential events an example here would be virus infections This package works to produce “pseudo random” numbers using a combination of a “Bitgenerator”and “generators” [3]. The word pseudo random relates to the fact that the package uses an algorithm to generate therandom numbers and so they can’t be considered truly random. Advantages of these types of random numbers is that they can be generated quickly. The series of numbers can also be saved to memory and recalled at a different time. One downside to these algorithms is that they are ‘periodic’ meaning that eventually the sequence of numbers will eventually repeat.


### Section 2 - Simple Random Data and Permutations functions


##### The Simple Random Data function in Numpy is made up of 4 functions. These functions are integers, random, choice and bytes. A breakdown of these 4 functions with examples can be seen below.

***

#### Integers

##### The integer function works by returning 'random integers' from 'low to high exclusive' or hight to low depending on if then enpoint is set to true. An example of this function can be seen below.

In [2]:
import numpy as np
rng = np.random.default_rng()
x = rng.integers(2, size= 20)
# The above will produce 20 integers (size = 20) between 0 and . This assumes the high= 2 the 2nd value between 0 and 1
x


array([0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1],
      dtype=int64)

In [3]:
x = rng.integers(10, size= 20)
# The above will produce 20 integers between 0 and 9 again assuming the high =9 i.e the 10th value between 0 and 9
x

array([6, 0, 5, 7, 6, 1, 5, 1, 5, 7, 0, 1, 2, 9, 1, 8, 5, 7, 6, 1],
      dtype=int64)

In [5]:
x = rng.integers(20,high=30,size= 20,)
# This numpy array specifys a high value of 30 and a low value of 20 and so will give 20 integers between 20 and 29
x

array([28, 21, 22, 26, 25, 29, 24, 22, 23, 25, 24, 21, 24, 23, 29, 21, 27,
       24, 23, 20], dtype=int64)

##### Random

##### This function works by generating a number of random floating point number between 0 and 1.  In older versions of Numpy this function was given as random.rand however is now generator.random. The inputs for random are (no of rows, no of columns) see example below

In [7]:
# we are going to import numpy and define rng as the generator
import numpy as np
rng= np.random.default_rng()
x= rng.random((6, 3))
x
# The above code will produce 6 rows x 3 columns of floating point numbers between 0 and 1.

array([[3.88785325e-01, 9.64191462e-01, 5.89719305e-01],
       [5.87165695e-01, 7.58638976e-01, 1.24739656e-01],
       [1.46104929e-01, 2.27959905e-04, 1.73276871e-01],
       [2.54449667e-01, 2.09705193e-01, 1.63751737e-01],
       [6.07380410e-01, 1.48550859e-01, 5.01008009e-01],
       [2.40271622e-01, 8.76931054e-01, 1.52002921e-01]])

In [8]:
# In order to increase the range that the .random function can use it is possible to multiply the funtion by whatever
# number the user would like to increase the range to . See below

In [9]:
x= 100 * rng.random((6,3))
x
# The above code is now selecting floating point numbers between the values of 0 and 100.

array([[20.29946527, 69.05692953, 27.91704664],
       [52.74584505, 73.91873238, 86.15712437],
       [33.93240164, 14.30760152, 66.88907347],
       [67.28463538, 20.63589101, 83.58627505],
       [59.61363582, 77.44231152, 76.11999812],
       [35.14482814, 19.12089075, 11.97323873]])

##### Choice 

##### The choice function allows the user to generate a random sample from a 1 dimensional array. See below examples 

In [11]:
import numpy as np
rng = np.random.default_rng()
x= rng.choice (15, 6)
x
# The above generates a uniform distribution of 6 values between 0 and 15 exclusive

array([11,  6,  9,  6,  7, 13], dtype=int64)

In [19]:
# The below displays a non uniform distribution of 6 values between 0 and 15 exclusive
x= rng.choice (6, 6, p= [0.1, 0.1, 0.2,0.4, 0.1, 0.1])
x
# The 'p' in this case represents the probabilty. as can be seen from the p values they are not
# evenly distributed and so do not produce a uniform output of values. 

array([0, 3, 3, 3, 2, 3], dtype=int64)

##### Bytes

##### The bytes sub function in the simple random data function is to return random bytes and this function takes only one argument and that being the number of bytes the user would like to produce. See below an example.

In [21]:
import numpy as np
rng= np.random.default_rng()
x= rng.bytes(20)
# The number of bytes that the user wants to display is added
x

b'}\x0c~}\t\xfe=\r\xcc\x16I\xebg\xc0\xb1\x96\x1d\xc3 \x85'

***
##### Permutations
 


##### A permutation can be defined as multitude of possible was a series can be re-arranged, arranged and ordered. There are 2 types of permutation functions in the numpy.random package. These are 'shuffle' and 'permutation'. These two functions are described further below.

##### Shuffle

##### The Shuffle function is used to shuffle a pre-ordered sequence of values. This function requires the use of a numpy range of values in its input The code below shows two examples of the shuffle funtion being used.


In [9]:
# We start by importing numpy
import numpy as np
#we then define the random number generator (rng)
rng= np.random.default_rng()
# We enter the range of values that the user wants to 
arr = np.arange(20)
x = rng.shuffle(arr)
arr

array([19,  3, 15,  4,  0, 18, 13,  8, 17,  6, 11, 16, 10, 14,  1, 12,  2,
        9,  7,  5])

##### As can be seen above, the shuffle function takes every value within the range that the user chooses and shuffles it outputting all the values in different order.

##### Permutation

##### This function can perform two outputs. The first will randomly permuting a sequence of values and the second will be returning a permuted range. 

In [10]:
import numpy as np
rng= np.random.default_rng()
x = rng.permutation(20)
# This command produces the permutation using np.arange with value 20 (The same as the shuffle function)
x

array([ 1, 14, 17, 12, 11,  9,  2,  3, 15,  7, 10,  0,  6, 16,  8, 18, 19,
        4,  5, 13])

In [17]:
x = np.arange(16).reshape((4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

***

### Section 3- Distributions

##### The numpy.random package provide a wide array of distributions that can be 